version: '1.0'
stages:
- checkout
- build
steps:
  main_clone:
    title: Cloning main repository...
    type: git-clone
    stage: checkout
    repo: 'NagaAbishek/codefresh-pipelines'
    revision: 'main'
    git: github
  build_my_app:
    title: Building Node.Js Docker Image
    type: build
    image_name: my-app
    working_directory: '${{main_clone}}'
    tag: 'master'
    dockerfile: Dockerfile
    
