version: '1.0'
stages:
- checkout
- build
- push
steps:
  main_clone:
    title: Cloning repository
    type: git-clone
    repo: 'NagaAbishek/codefresh-pipelines'
    revision: 'master'
    git: github
    stage: clone
  build_my_app:
    title: Building Docker Image
    type: build
    stage: build
    image_name: codefresh-pipelines
    working_directory: '.'
    tag: 'main'
    dockerfile: Dockerfile
  push_to_my_registry:
    stage: 'push'
    type: push
    title: Pushing to a registry
    candidate: ${{build_my_app}}
    tag: 'v1.0.0'
    registry: codefresh-docker-image
    image_name: naga/codefresh-pipelines
